version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./internal/db/init/:/docker-entrypoint-initdb.d/
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U felix -d wbstore -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5


  nats:
    image: nats:latest
    command: -js
    ports:
      - ${NATS_PORTS}
      - "8222:8222"


  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NATS_URL: ${NATS_URL}
      SERVER_PORT: ${SERVER_PORT}
    depends_on:
      migrator:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
      
  migrator:
      image: migrate/migrate
      volumes:
        - ./internal/db/migrations:/migrations
      depends_on:
        postgres:
          condition: service_healthy
      environment:
        DATABASE_URL: ${DATABASE_URL}
      command:
        - "-path=/migrations"
        - "-database=${DATABASE_URL}"
        - "up"
      restart: on-failure
volumes:
  pgdata:
